g++ 1_throw_exception.cpp -o 1_throw_exception.o
g++ 2_my_exception.cpp -o 2_my_exception.o
